apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-results
  namespace: arc-runner
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
